### ISSUE TITLE
can u add primaryInitialSize?

### ISSUE THREAD

**Issue by arcifius** [zesik/react-splitter-layout#4] opened 2017-10-14 02:41 UTC
It is nice to have secondaryInitialSize but I want to start with the first pane having 200px of height... A primaryInitialSize should solve :D

**Comment by zesik** [comment] 2017-10-16 13:02
Hi arcifius,

By design, size of primary pane is flexible and cannot be set with initial size. Could you please try to use `secondaryInitialSize` and swap primary and secondary with `primaryIndex`?

**Comment by zesik** [comment] 2017-11-14 12:18
Closing this due to no further information.

**Closed by zesik** 2017-11-14 12:18 UTC
