### ISSUE TITLE
Resizing isn't working if the right pane contains IFrame 

### ISSUE THREAD

**Issue by VimalkumarK** [zesik/react-splitter-layout#28] opened 2018-11-16 09:56 UTC
Hi,

I am facing a big challenge on resizing the pane using splitter when the right pane contains the IFrame. It's the same issue on IE,Chrome and Firefox.
kindly help me to get through the issue. Thanks.

**Comment by pranayrauthu** [comment] 2019-01-01 15:13
I am facing the same problem.

**Comment by zesik** [comment] 2019-02-09 07:22
Duplicate of #7.

Also, I added another way of doing this in examples. See examples in `v4` branch (or `master` after it is merged).

**Closed** 2019-02-09 07:22 UTC
